import { Contract } from './types';

export const CONTRACT_POOL: Omit<Contract, 'startDay' | 'progressDays' | 'status'>[] = [
  {
    id: 'profit_margins',
    title: 'Profit Margins',
    description: 'Maintain net income > $300/day for 7 days.',
    conditions: [{ metric: 'profit', operator: '>', value: 300 }],
    durationDays: 7,
    reward: { money: 3000 },
    penalty: { money: -750 },
  },
  {
    id: 'family_paradise',
    title: 'Family Paradise',
    description: 'Have 5+ families AND reputation > 40 for 7 days.',
    conditions: [
      { metric: 'segment_count', operator: '>=', value: 5, segment: 'family' },
      { metric: 'reputation', operator: '>', value: 40 },
    ],
    durationDays: 7,
    reward: { money: 4500, reputation: 5 },
    penalty: { reputation: -3 },
  },
  {
    id: 'storm_survivor',
    title: 'Storm Survivor',
    description: 'Keep reputation above 30 for 5 days (even through storms).',
    conditions: [{ metric: 'reputation', operator: '>=', value: 30 }],
    durationDays: 5,
    reward: { money: 2250 },
    penalty: { money: -500 },
  },
  {
    id: 'vip_satisfaction',
    title: 'VIP Satisfaction',
    description: 'Have 3+ VIP guests with avg happiness > 60 for 5 days.',
    conditions: [
      { metric: 'segment_count', operator: '>=', value: 3, segment: 'vip' },
      { metric: 'happiness', operator: '>=', value: 60 },
    ],
    durationDays: 5,
    reward: { money: 6000 },
    penalty: { reputation: -5 },
  },
  {
    id: 'budget_resort',
    title: 'Budget Resort',
    description: 'Maintain occupancy > 60% for 7 days.',
    conditions: [{ metric: 'occupancy', operator: '>=', value: 60 }],
    durationDays: 7,
    reward: { money: 3750 },
    penalty: { money: -600 },
  },
  {
    id: 'five_star_service',
    title: 'Five Star Service',
    description: 'Reach reputation 70+ AND happiness > 65 simultaneously for 5 days.',
    conditions: [
      { metric: 'reputation', operator: '>=', value: 70 },
      { metric: 'happiness', operator: '>', value: 65 },
    ],
    durationDays: 5,
    reward: { money: 7500, reputation: 10 },
    penalty: { reputation: -5, socialHeat: 5 },
  },
  {
    id: 'full_house',
    title: 'Full House',
    description: 'Maintain 80%+ occupancy for 5 days.',
    conditions: [{ metric: 'occupancy', operator: '>=', value: 80 }],
    durationDays: 5,
    reward: { money: 5000 },
    penalty: { money: -750 },
  },
  {
    id: 'steady_growth',
    title: 'Steady Growth',
    description: 'Keep net income positive for 10 days straight.',
    conditions: [{ metric: 'profit', operator: '>', value: 0 }],
    durationDays: 10,
    reward: { money: 3000, reputation: 3 },
    penalty: { money: -500 },
  },
];
